---
interval: 1m
push: http://centos.schou.me:9550/collector/site/office
devices:
  - name: basement
    enabled: true
    host: 10.12.254.246
    copy-oids-from: router

    # Note that the passwords do not copy.
    # So you will need to include them for each device.

    # Authentication details
    community: public
    version: 3
    username: paul
    auth-proto: SHA1
    prov-proto: AES
    auth-password: authpass
    priv-password: encpass

  - name: parkinglot
    enabled: true
    host: 10.12.254.192
    copy-oids-from: router

  - name: serverroom
    enabled: true
    host: 10.12.10.20
    copy-oids-from: router

  - name: backoffice
    enabled: true
    host: 10.12.10.11
    copy-oids-from: router

  - name: mainrouter
    enabled: true
    host: 10.12.0.1
    port: 161
    protocol: udp

    # Authentication details
    community: public
    version: 3
    username: paul
    auth-proto: SHA1
    prov-proto: AES
    auth-password: authpass
    priv-password: encpass

    # Statically loaded labels for the device
    # static-labels:
    #   replica: primary
    #   inventory: RA123456
    static-status:
      up: 1

    # Dynamically loaded labels for the device
    labels:
      identity: .1.3.6.1.2.1.1.5.0
      model: .1.3.6.1.2.1.1.1.0
    #  contact: .1.3.6.1.2.1.1.4.0
    #  location: .1.3.6.1.2.1.1.6.0
    status:
      uptime: .1.3.6.1.2.1.1.3.0
      memory_used: .1.3.6.1.2.1.25.2.3.1.6.65536
      memory_total: .1.3.6.1.2.1.25.2.3.1.5.65536

    groupings:
      - group: interfaces
        priority: true
        labels:
          name: .1.3.6.1.2.1.31.1.1.1.1
        status:
          ifInErrors: .1.3.6.1.2.1.2.2.1.14
          ifOutErrors: .1.3.6.1.2.1.2.2.1.20
          ifType: .1.3.6.1.2.1.2.2.1.3
          ifHighSpeed: .1.3.6.1.2.1.31.1.1.1.15
          ifHCOutOctets: .1.3.6.1.2.1.31.1.1.1.10
          ifHCInOctets: .1.3.6.1.2.1.31.1.1.1.6
      - group: routes_v4
        index: route
        labels:
          dest: .1.3.6.1.2.1.4.24.4.1.1
          nextHop: .1.3.6.1.2.1.4.24.4.1.4
          mask: .1.3.6.1.2.1.4.24.4.1.2
        status:
          active: .1.3.6.1.2.1.4.24.4.1.16
          ifIndex: .1.3.6.1.2.1.4.24.4.1.5
          age: .1.3.6.1.2.1.4.24.4.1.8
      - group: routes_v6
        index: route
        labels:
          dest: .1.3.6.1.2.1.55.1.11.1.1 hex
          nextHop: .1.3.6.1.2.1.55.1.11.1.5 hex
        status:
          pfxLength: .1.3.6.1.2.1.55.1.8.1.2
          valid: .1.3.6.1.2.1.55.1.11.1.14
          ifIndex: .1.3.6.1.2.1.55.1.11.1.4
          age: .1.3.6.1.2.1.55.1.11.1.9
        static-status:
          up: 1
      - group: cpu
        status:
          load: .1.3.6.1.2.1.25.3.3.1.2
      - group: capsman
        index: mac
        labels:
          # mac_address: .1.3.6.1.4.1.14988.1.1.1.5.1.1 hex
          ssid: .1.3.6.1.4.1.14988.1.1.1.5.1.12
        status:
          uptime: .1.3.6.1.4.1.14988.1.1.1.5.1.3
          tx_bytes: .1.3.6.1.4.1.14988.1.1.1.5.1.4
          rx_bytes: .1.3.6.1.4.1.14988.1.1.1.5.1.5
          tx_packets: .1.3.6.1.4.1.14988.1.1.1.5.1.6
          rx_packets: .1.3.6.1.4.1.14988.1.1.1.5.1.7
          tx_rate: .1.3.6.1.4.1.14988.1.1.1.5.1.8
          rx_rate: .1.3.6.1.4.1.14988.1.1.1.5.1.9
          tx_signal: .1.3.6.1.4.1.14988.1.1.1.5.1.10
          rx_signal: .1.3.6.1.4.1.14988.1.1.1.5.1.11
      - group: wireless
        index: mac
        labels:
          routeros_version: .1.3.6.1.4.1.14988.1.1.1.2.1.10
          radio_name: .1.3.6.1.4.1.14988.1.1.1.2.1.20
        status:
          signal_strength: .1.3.6.1.4.1.14988.1.1.1.2.1.3
          tx_signal_strength: .1.3.6.1.4.1.14988.1.1.1.2.1.19
          tx_bytes: .1.3.6.1.4.1.14988.1.1.1.2.1.4
          rx_bytes: .1.3.6.1.4.1.14988.1.1.1.2.1.5
          tx_packets: .1.3.6.1.4.1.14988.1.1.1.2.1.6
          rx_packets: .1.3.6.1.4.1.14988.1.1.1.2.1.7
          tx_rate: .1.3.6.1.4.1.14988.1.1.1.2.1.8
          rx_rate: .1.3.6.1.4.1.14988.1.1.1.2.1.9
          uptime: .1.3.6.1.4.1.14988.1.1.1.2.1.11
          signal_to_noise: .1.3.6.1.4.1.14988.1.1.1.2.1.12
          tx_signal_strength_ch0: .1.3.6.1.4.1.14988.1.1.1.2.1.13
          signal_strength_ch0: .1.3.6.1.4.1.14988.1.1.1.2.1.14
          tx_signal_strength_ch1: .1.3.6.1.4.1.14988.1.1.1.2.1.15
          signal_strength_ch1: .1.3.6.1.4.1.14988.1.1.1.2.1.16
          tx_signal_strength_ch2: .1.3.6.1.4.1.14988.1.1.1.2.1.17
          signal_strength_ch2: .1.3.6.1.4.1.14988.1.1.1.2.1.18
