---
interval: 1m
push: http://centos.schou.me:9550/collector/site/home
devices:
  - name: basement
    enabled: true
    host: 10.12.254.246
    copy-oids-from: router

    # Note that the passwords do not copy.
    # So you will need to include them for each device.

    # Authentication details
    community: public
    version: 3
    username: paul
    auth-proto: SHA1
    prov-proto: AES
    auth-password: authpass
    priv-password: encpass

  - name: outdoors
    enabled: true
    host: 10.12.254.192
    copy-oids-from: router

  - name: upstairs
    enabled: true
    host: 10.12.10.20
    copy-oids-from: router

  - name: livingroom
    enabled: true
    host: 10.12.10.11
    copy-oids-from: router

  - name: router
    enabled: true
    host: 10.12.0.1
    port: 161
    protocol: udp

    # Authentication details
    community: public
    version: 3
    username: paul
    auth-proto: SHA1
    prov-proto: AES
    auth-password: authpass
    priv-password: encpass

    # Statically loaded labels for the device
    # static-labels:
    #   replica: primary
    #   inventory: RA123456
    static-status:
      up: 1

    # Dynamically loaded labels for the device
    labels:
      identity: .1.3.6.1.2.1.1.5.0
      model: .1.3.6.1.2.1.1.1.0
    #  contact: .1.3.6.1.2.1.1.4.0
    #  location: .1.3.6.1.2.1.1.6.0
    status:
      uptime: .1.3.6.1.2.1.1.3.0
      memory_used: .1.3.6.1.2.1.25.2.3.1.6.65536
      memory_total: .1.3.6.1.2.1.25.2.3.1.5.65536

    groupings:
      - group: interfaces
        priority: true
        labels:
          name: .1.3.6.1.2.1.31.1.1.1.1
        status:
          ifInErrors: .1.3.6.1.2.1.2.2.1.14
          ifOutErrors: .1.3.6.1.2.1.2.2.1.20
          ifType: .1.3.6.1.2.1.2.2.1.3
          ifHighSpeed: .1.3.6.1.2.1.31.1.1.1.15
          ifHCOutOctets: .1.3.6.1.2.1.31.1.1.1.10
          ifHCInOctets: .1.3.6.1.2.1.31.1.1.1.6
      - group: routes_v4
        index: route
        labels:
          dest: .1.3.6.1.2.1.4.24.4.1.1
          nextHop: .1.3.6.1.2.1.4.24.4.1.4
          mask: .1.3.6.1.2.1.4.24.4.1.2
        status:
          active: .1.3.6.1.2.1.4.24.4.1.16
          ifIndex: .1.3.6.1.2.1.4.24.4.1.5
          age: .1.3.6.1.2.1.4.24.4.1.8
      - group: routes_v6
        index: route
        labels:
          dest: .1.3.6.1.2.1.55.1.11.1.1 hex
          nextHop: .1.3.6.1.2.1.55.1.11.1.5 hex
        status:
          pfxLength: .1.3.6.1.2.1.55.1.8.1.2
          valid: .1.3.6.1.2.1.55.1.11.1.14
          ifIndex: .1.3.6.1.2.1.55.1.11.1.4
          age: .1.3.6.1.2.1.55.1.11.1.9
        static-status:
          up: 1
      - group: cpu
        status:
          load: .1.3.6.1.2.1.25.3.3.1.2
      - group: capsman
        index: mac
        labels:
          # mac_address: .1.3.6.1.4.1.14988.1.1.1.5.1.1 hex
          ssid: .1.3.6.1.4.1.14988.1.1.1.5.1.12
        status:
          uptime: .1.3.6.1.4.1.14988.1.1.1.5.1.3
          tx_bytes: .1.3.6.1.4.1.14988.1.1.1.5.1.4
          rx_bytes: .1.3.6.1.4.1.14988.1.1.1.5.1.5
          tx_packets: .1.3.6.1.4.1.14988.1.1.1.5.1.6
          rx_packets: .1.3.6.1.4.1.14988.1.1.1.5.1.7
          tx_rate: .1.3.6.1.4.1.14988.1.1.1.5.1.8
          rx_rate: .1.3.6.1.4.1.14988.1.1.1.5.1.9
          tx_signal: .1.3.6.1.4.1.14988.1.1.1.5.1.10
          rx_signal: .1.3.6.1.4.1.14988.1.1.1.5.1.11
      - group: wireless
        index: mac
        labels:
          routeros_version: .1.3.6.1.4.1.14988.1.1.1.2.1.10
          radio_name: .1.3.6.1.4.1.14988.1.1.1.2.1.20
        status:
          signal_strength: .1.3.6.1.4.1.14988.1.1.1.2.1.3
          tx_signal_strength: .1.3.6.1.4.1.14988.1.1.1.2.1.19
          tx_bytes: .1.3.6.1.4.1.14988.1.1.1.2.1.4
          rx_bytes: .1.3.6.1.4.1.14988.1.1.1.2.1.5
          tx_packets: .1.3.6.1.4.1.14988.1.1.1.2.1.6
          rx_packets: .1.3.6.1.4.1.14988.1.1.1.2.1.7
          tx_rate: .1.3.6.1.4.1.14988.1.1.1.2.1.8
          rx_rate: .1.3.6.1.4.1.14988.1.1.1.2.1.9
          uptime: .1.3.6.1.4.1.14988.1.1.1.2.1.11
          signal_to_noise: .1.3.6.1.4.1.14988.1.1.1.2.1.12
          tx_signal_strength_ch0: .1.3.6.1.4.1.14988.1.1.1.2.1.13
          signal_strength_ch0: .1.3.6.1.4.1.14988.1.1.1.2.1.14
          tx_signal_strength_ch1: .1.3.6.1.4.1.14988.1.1.1.2.1.15
          signal_strength_ch1: .1.3.6.1.4.1.14988.1.1.1.2.1.16
          tx_signal_strength_ch2: .1.3.6.1.4.1.14988.1.1.1.2.1.17
          signal_strength_ch2: .1.3.6.1.4.1.14988.1.1.1.2.1.18

# This above config produces output like the following:
# centos$ curl http://localhost:9070/metrics
#
# # Device livingroom (10.12.10.11)
# snmp_up{identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",device_host="10.12.10.11",device_name="livingroom"} 1 1610589960000
# snmp_uptime{model="RouterOS RBcAPGi-5acD2nD",device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom"} 336580600 1610589960000
# snmp_memory_used{device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",device_host="10.12.10.11"} 51992 1610589960000
# snmp_memory_total{device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",device_host="10.12.10.11"} 131072 1610589960000
# snmp_interfaces_ifOutErrors{device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="wlan1",oid_index="1",device_host="10.12.10.11"} 0 1610589960000
# snmp_interfaces_ifOutErrors{device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="wlan2",oid_index="2",device_host="10.12.10.11"} 0 1610589960000
# snmp_interfaces_ifOutErrors{device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="ether1",oid_index="3"} 0 1610589960000
# snmp_interfaces_ifOutErrors{device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="ether2",oid_index="4"} 0 1610589960000
# snmp_interfaces_ifOutErrors{oid_index="5",name="bridge1",device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD"} 0 1610589960000
# snmp_interfaces_ifOutErrors{identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",oid_index="6",name="vlan10",device_host="10.12.10.11",device_name="livingroom"} 0 1610589960000
# snmp_interfaces_ifType{device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="wlan1",oid_index="1"} 71 1610589960000
# snmp_interfaces_ifType{identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="wlan2",oid_index="2",device_host="10.12.10.11",device_name="livingroom"} 71 1610589960000
# snmp_interfaces_ifType{device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",oid_index="3",name="ether1",device_host="10.12.10.11"} 6 1610589960000
# snmp_interfaces_ifType{device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="ether2",oid_index="4",device_host="10.12.10.11"} 6 1610589960000
# snmp_interfaces_ifType{device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="bridge1",oid_index="5"} 209 1610589960000
# snmp_interfaces_ifType{model="RouterOS RBcAPGi-5acD2nD",name="vlan10",oid_index="6",device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom"} 135 1610589960000
# snmp_interfaces_ifHighSpeed{device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="wlan1",oid_index="1"} 50 1610589960000
# snmp_interfaces_ifHighSpeed{device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",device_host="10.12.10.11",oid_index="2",name="wlan2"} 50 1610589960000
# snmp_interfaces_ifHighSpeed{oid_index="3",model="RouterOS RBcAPGi-5acD2nD",device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",name="ether1"} 1000 1610589960000
# snmp_interfaces_ifHighSpeed{model="RouterOS RBcAPGi-5acD2nD",name="ether2",oid_index="4",device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom"} 100 1610589960000
# snmp_interfaces_ifHighSpeed{device_name="livingroom",identity="LivingRoom",name="bridge1",oid_index="5",model="RouterOS RBcAPGi-5acD2nD",device_host="10.12.10.11"} 0 1610589960000
# snmp_interfaces_ifHighSpeed{device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="vlan10",oid_index="6"} 0 1610589960000
# snmp_interfaces_ifHCOutOctets{oid_index="1",device_host="10.12.10.11",device_name="livingroom",identity="LivingRoom",model="RouterOS RBcAPGi-5acD2nD",name="wlan1"} 7510759399 1610589960000
